version: "2"
run:
  build-tags:
    - bench
    - ""
  tests: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        Main:
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - golang.org/x/
            - github.com/stretchr/testify
            - github.com/cheggaaa/pb/v3
            - github.com/spf13/pflag
            - github.com/spf13/viper
            - github.com/jmoiron/sqlx
            - github.com/mattn/go-sqlite3
            - github.com/go-sql-driver/mysql
            - github.com/DATA-DOG/go-sqlmock
            - github.com/jackc/pgx/v5
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/app
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/config
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/data
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/interfaces
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/logger
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/server/http
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/storage
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/storage/memory
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/storage/sql
        Test:
          files:
            - $test
          allow:
            - $gostd
            - golang.org/x/
            - github.com/stretchr/testify
            - go.uber.org/goleak
            - github.com/spf13/pflag
            - github.com/spf13/viper
            - github.com/jmoiron/sqlx
            - github.com/mattn/go-sqlite3
            - github.com/go-sql-driver/mysql
            - github.com/DATA-DOG/go-sqlmock
            - github.com/jackc/pgx/v5
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/app
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/config
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/data
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/interfaces
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/logger
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/server/http
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/storage
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/storage/memory
            - github.com/evr-gh/otus-go-hw/hw12_13_14_15_calendar/internal/storage/sql
    funlen:
      lines: 150
      statements: 80
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
