// Calendar protobuf

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: internal/server/rpc/protobuf/calendar.proto

package calendarrpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nill) Reset() {
	*x = Nill{}
	mi := &file_internal_server_rpc_protobuf_calendar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nill) ProtoMessage() {}

func (x *Nill) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_rpc_protobuf_calendar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nill.ProtoReflect.Descriptor instead.
func (*Nill) Descriptor() ([]byte, []int) {
	return file_internal_server_rpc_protobuf_calendar_proto_rawDescGZIP(), []int{0}
}

type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Time           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Duration       *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Owner          string                 `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Notifyleadtime *durationpb.Duration   `protobuf:"bytes,7,opt,name=notifyleadtime,proto3" json:"notifyleadtime,omitempty"`
	Sheduled       bool                   `protobuf:"varint,8,opt,name=sheduled,proto3" json:"sheduled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_internal_server_rpc_protobuf_calendar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_rpc_protobuf_calendar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_internal_server_rpc_protobuf_calendar_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Event) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Event) GetNotifyleadtime() *durationpb.Duration {
	if x != nil {
		return x.Notifyleadtime
	}
	return nil
}

func (x *Event) GetSheduled() bool {
	if x != nil {
		return x.Sheduled
	}
	return false
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_internal_server_rpc_protobuf_calendar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_rpc_protobuf_calendar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_internal_server_rpc_protobuf_calendar_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_internal_server_rpc_protobuf_calendar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_rpc_protobuf_calendar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_internal_server_rpc_protobuf_calendar_proto_rawDescGZIP(), []int{3}
}

func (x *Id) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_internal_server_rpc_protobuf_calendar_proto protoreflect.FileDescriptor

const file_internal_server_rpc_protobuf_calendar_proto_rawDesc = "" +
	"\n" +
	"+internal/server/rpc/protobuf/calendar.proto\x12\bcalendar\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x06\n" +
	"\x04Nill\"\xab\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12A\n" +
	"\x0enotifyleadtime\x18\a \x01(\v2\x19.google.protobuf.DurationR\x0enotifyleadtime\x12\x1a\n" +
	"\bsheduled\x18\b \x01(\bR\bsheduled\"\x1d\n" +
	"\x05Error\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2\xd5\x02\n" +
	"\vApplication\x121\n" +
	"\vCreateEvent\x12\x0f.calendar.Event\x1a\x0f.calendar.Event\"\x00\x12,\n" +
	"\tReadEvent\x12\f.calendar.Id\x1a\x0f.calendar.Event\"\x00\x121\n" +
	"\vUpdateEvent\x12\x0f.calendar.Event\x1a\x0f.calendar.Event\"\x00\x121\n" +
	"\vDeleteEvent\x12\x0f.calendar.Event\x1a\x0f.calendar.Event\"\x00\x129\n" +
	"\n" +
	"ListEvents\x12\x16.google.protobuf.Empty\x1a\x0f.calendar.Event\"\x000\x01\x12D\n" +
	"\x15ListNotSheduledEvents\x12\x16.google.protobuf.Empty\x1a\x0f.calendar.Event\"\x000\x01B\x13Z\x11./;calendarrpcapib\x06proto3"

var (
	file_internal_server_rpc_protobuf_calendar_proto_rawDescOnce sync.Once
	file_internal_server_rpc_protobuf_calendar_proto_rawDescData []byte
)

func file_internal_server_rpc_protobuf_calendar_proto_rawDescGZIP() []byte {
	file_internal_server_rpc_protobuf_calendar_proto_rawDescOnce.Do(func() {
		file_internal_server_rpc_protobuf_calendar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_server_rpc_protobuf_calendar_proto_rawDesc), len(file_internal_server_rpc_protobuf_calendar_proto_rawDesc)))
	})
	return file_internal_server_rpc_protobuf_calendar_proto_rawDescData
}

var file_internal_server_rpc_protobuf_calendar_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_server_rpc_protobuf_calendar_proto_goTypes = []any{
	(*Nill)(nil),                  // 0: calendar.Nill
	(*Event)(nil),                 // 1: calendar.Event
	(*Error)(nil),                 // 2: calendar.Error
	(*Id)(nil),                    // 3: calendar.Id
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 5: google.protobuf.Duration
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_internal_server_rpc_protobuf_calendar_proto_depIdxs = []int32{
	4, // 0: calendar.Event.time:type_name -> google.protobuf.Timestamp
	5, // 1: calendar.Event.duration:type_name -> google.protobuf.Duration
	5, // 2: calendar.Event.notifyleadtime:type_name -> google.protobuf.Duration
	1, // 3: calendar.Application.CreateEvent:input_type -> calendar.Event
	3, // 4: calendar.Application.ReadEvent:input_type -> calendar.Id
	1, // 5: calendar.Application.UpdateEvent:input_type -> calendar.Event
	1, // 6: calendar.Application.DeleteEvent:input_type -> calendar.Event
	6, // 7: calendar.Application.ListEvents:input_type -> google.protobuf.Empty
	6, // 8: calendar.Application.ListNotSheduledEvents:input_type -> google.protobuf.Empty
	1, // 9: calendar.Application.CreateEvent:output_type -> calendar.Event
	1, // 10: calendar.Application.ReadEvent:output_type -> calendar.Event
	1, // 11: calendar.Application.UpdateEvent:output_type -> calendar.Event
	1, // 12: calendar.Application.DeleteEvent:output_type -> calendar.Event
	1, // 13: calendar.Application.ListEvents:output_type -> calendar.Event
	1, // 14: calendar.Application.ListNotSheduledEvents:output_type -> calendar.Event
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_server_rpc_protobuf_calendar_proto_init() }
func file_internal_server_rpc_protobuf_calendar_proto_init() {
	if File_internal_server_rpc_protobuf_calendar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_server_rpc_protobuf_calendar_proto_rawDesc), len(file_internal_server_rpc_protobuf_calendar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_server_rpc_protobuf_calendar_proto_goTypes,
		DependencyIndexes: file_internal_server_rpc_protobuf_calendar_proto_depIdxs,
		MessageInfos:      file_internal_server_rpc_protobuf_calendar_proto_msgTypes,
	}.Build()
	File_internal_server_rpc_protobuf_calendar_proto = out.File
	file_internal_server_rpc_protobuf_calendar_proto_goTypes = nil
	file_internal_server_rpc_protobuf_calendar_proto_depIdxs = nil
}
